# Example application deployment using Bunny IPs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 8080
        env:
        # Method 1: Environment variable with all IPs
        - name: TRUSTED_PROXY_IPS
          valueFrom:
            configMapKeyRef:
              name: bunny-trusted-ips
              key: trusted_ips
        volumeMounts:
        # Method 2: File mount
        - name: trusted-ips-file
          mountPath: /etc/app/trusted-ips
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: trusted-ips-file
        configMap:
          name: bunny-trusted-ips
          items:
          - key: trusted_ips
            path: trusted_ips.txt
