# Example application deployment using Bunny IPs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
  labels:
    app.kubernetes.io/name: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
        env:
        # Method 1: Environment variable with all IPs
        - name: TRUSTED_PROXY_IPS
          valueFrom:
            configMapKeyRef:
              name: bunny-trusted-ips
              key: TRUSTED_PROXY_IP
        volumeMounts:
        # Method 2: File mount
        - name: trusted-ips-file
          mountPath: /etc/app/trusted-ips
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: trusted-ips-file
        configMap:
          name: bunny-trusted-ips
          items:
          - key: TRUSTED_PROXY_IP
            path: trusted_ips.txt
